@startuml PyGameMal
title PyGameMal

class Sprite{
    rect: Rect
    image: Surface
    {abstract} update(): None
    'add(*groups): None
    'remove(*groups): None
    'kill(): None
    'alive(): bool
    'groups(): list<Group>
}

class SpilleObjekt1{
    app: App
    update(): None
}

class SpilleObjekt2{
    app: App
    update(): None
}

class App{
    clock: Clock
    screen: Surface
    running: bool
    all_sprites: Group
    handle_events(): None
    update(): None
    draw(): None
    run(): None
}

Sprite <|-- SpilleObjekt1
Sprite <|-- SpilleObjekt2
App *--Sprite
App --* SpilleObjekt1
App --* SpilleObjekt2

@enduml
